require("core.options")
require("core.mappings")
require("core.autocmds")

require("plugins.lazy")

require("plugins.theme")

require("plugins.which-key")
require("plugins.lualine")
require("plugins.neo-tree")
require("plugins.toggleterm")
require("plugins.lsp")
require("plugins.surround")
require("plugins.align")
require("plugins.sessions")
require("plugins.bracketed")

require("plugins.mappings")
-- require('sessions')
-- require('surround')
-- require('align')
-- require('comment')
-- require('lsp')
-- require('completion')
-- require('treesitter')
-- require('tele')
-- require('debugger')
-- require('project')
